# Generated by Django 5.0.1 on 2024-01-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField()),
                ('bot_response', models.TextField()),
                ('date_only', models.DateField(auto_now_add=True)),
                ('time_only', models.TimeField(auto_now_add=True)),
                ('is_first_message', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_only', models.DateField(auto_now_add=True)),
                ('time_only', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('file_url', models.URLField(null=True)),
            ],
        ),
    ]
