# Generated by Django 5.0.1 on 2024-01-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyquestion',
            name='date_only',
            field=models.DateField(blank=True, null=True),
        ),
    ]
