# Generated by Django 5.0.1 on 2024-01-24 23:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_historyquestion_date_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyquestion',
            name='date_only',
        ),
        migrations.AddField(
            model_name='historyquestion',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
