# Generated by Django 5.0.1 on 2024-01-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_historyquestion_date_only_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyquestion',
            old_name='date',
            new_name='date_only',
        ),
    ]
