# Generated by Django 5.0.1 on 2024-01-25 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_date_historyquestion_date_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyquestion',
            old_name='message',
            new_name='first_question',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_first_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_question',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
