# Generated by Django 5.0.1 on 2024-01-25 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_message_historyquestion_first_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyquestion',
            old_name='first_question',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_first_message',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_question',
        ),
    ]
