# Generated by Django 5.0.1 on 2024-01-25 01:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_first_question_historyquestion_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_question',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
