# Generated by Django 5.0.1 on 2024-01-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversation_user_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyquestion',
            name='is_first_message',
            field=models.BooleanField(default=False),
        ),
    ]
