# Generated by Django 5.0.1 on 2024-01-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_historyquestion_is_first_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyquestion',
            name='is_first_message',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_first_message',
            field=models.BooleanField(default=False),
        ),
    ]
